#! /bin/bash

cd ../bin

`cat ../sh/rmic-path` -classpath .:../../bayes/bin poker.server.base.impl.StatePlayer
`cat ../sh/rmic-path` -classpath .:../../bayes/bin poker.server.cluster.ClusterServerImpl
`cat ../sh/rmic-path` -classpath .:../../bayes/bin poker.server.log.LogServerImpl
`cat ../sh/rmic-path` -classpath .:../../bayes/bin poker.server.session.SessionServerImpl
