
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Sep 29 13:46:10 EDT 2005
//----------------------------------------------------

package poker.ai.rules;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GTEQ = 36;
  public static final int FOLD = 3;
  public static final int LTEQ = 35;
  public static final int SLASH = 9;
  public static final int UNTAB = 20;
  public static final int NOT = 40;
  public static final int AND = 10;
  public static final int LT = 33;
  public static final int IN = 39;
  public static final int LP = 26;
  public static final int OR = 11;
  public static final int ATOM = 21;
  public static final int TAB = 19;
  public static final int CALL = 5;
  public static final int RP = 27;
  public static final int LSB = 28;
  public static final int PLUS = 12;
  public static final int ASSIGN = 17;
  public static final int EOF = 0;
  public static final int CARD = 24;
  public static final int TRUE = 30;
  public static final int error = 1;
  public static final int CHECK = 6;
  public static final int NUMBER = 22;
  public static final int NEQ = 38;
  public static final int EQ = 37;
  public static final int ERROR = 25;
  public static final int COM = 18;
  public static final int ARROW = 15;
  public static final int COLON = 16;
  public static final int RSB = 29;
  public static final int STOP = 13;
  public static final int CURRENCY = 23;
  public static final int STRING = 7;
  public static final int FALSE = 31;
  public static final int CALLM = 8;
  public static final int GT = 34;
  public static final int FOLLOWS = 32;
  public static final int BET = 2;
  public static final int PRINT = 14;
  public static final int RAISE = 4;
}

